config/routes.rb
Bookasite::Application.routes.draw do
  root :to => 'series#index'

  # AJAX
  resources :boks

  match "/auth/:provider/callback" => "sessions#create"
  match "/cerrar" => "sessions#destroy", :as => :logout
  match "/identificarse" => "sessions#new", :as => :login
  match "/enter/:id" => "sessions#enter", :as => :enter
  match "/work" => "jobs#work", :as => :work
  match "/admin" => "admin/versions#index"

  # PUBLIC
    scope(:path_names => {:new => "nuevo", :edit => "editar"}) do
    scope "/admin" do
      resources :pages, :path => 'paginas'
      resources :users, :path => 'participantes' do
        resources :invitations, :path => 'invitaciones'
        resources :email_notifications, :path => 'email', :only => :create
      end
      resources :jobs, :path => 'trabajos'
      resources :activities, :path => 'actividad'
      resources :versions, :path => 'versiones'
      resources :notifications, :path => 'subscripciones'
    end

    scope "/models" do
      resources :topics, :only => :show
      resources :asambleas, :only => :show
      resources :calls, :only => :show
      resources :contents, :only => :show
      resources :comments, :only => :show
      resources :answers, :only => :show
    end

    resources :series

    resources :topics do
      resources :answers
      resources :comments
    end
    resources :answers do
      resources :comments
    end


    resources :projects, :path => '' do
      resources :permissions, :path => 'participantes'
      resources :contents, :path => 'materiales'
      resources :asambleas, :path => 'edicion' do
        resources :topics, :path => 't'
      end
      resources :calls, :path => "intro" do
        get :view, :on => :collection, :path => 'ver'
      end
      resources :proposals, :path => 'propuestas' do
        get :view, :on => :collection, :path => 'ver'
      end

    end
  end


end

app/models/content.rb
class Content < Bok
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  expose(:project) { Project.get params[:project_id] }
  #show
  expose(:serie) { project.serie }
  expose(:contents) { project.contents }
  expose(:content)

  def index
    redirect_to [project, project.contents.first]
  end

  def show
    if params[:project_id].blank?
      content = Content.find params[:id]
      redirect_to [content.project, content]
    end
  end
end

app/helpers/contents_helper.rb
# encoding: utf-8


module ContentsHelper
  def render_body(model)
    return if model.blank?
    if model.body.blank?
      title = model.respond_to?(:title) ? model.title :  'esta página'
      content_tag :div, "<De momento '#{title}' no tiene contenido>", :class => 'body'
    elsif model.content_type == 'text/html'
      content_tag :div, model.body.html_safe, :class => 'body'
    else
      content_tag :div, model.body, :class => 'body'
    end
  end

end

app/views/contents/_browser.html.erb
<ul class="browser">
  <h2>Materiales</h2>
  <% contents.each do |content| %>
      <%= content_tag_for :li, content do %>
          <h3><%= link_to content.title, [project, content] %></h3>
          <div class="authors"><%= content.authors %></div>
      <% end %>
  <% end %>
</ul>
<%= link_to image_tag('logos/LOGO-VIBOK.png', :alt => 'vibok', :id => 'logo-vibok'), 'http://www.edicionesvibok.net' %>

app/views/contents/_contents.html.erb
<%= content_for :navigation do %>
    <%= link_to image_tag('iconos/booka.jpg') %>
    <h2>Materiales</h2>
    <ul>
      <% @contents.each do |content| %>
          <%= content_tag_for :li, content do %>
              <%= link_to content.title, project_content_path(content.project, content),
                          :"data-page" => bok_path(content.id) %>
              <div class="property description"><%= content.description %></div>
              <div class="property authors"><%= content.authors %></div>
          <% end %>
      <% end %>
    </ul>
<% end %>

app/views/contents/_page.html.erb
<h1><%= @content.title %></h1>
<div class="authors"><%= @content.authors %></div>
<%= @content.body.html_safe %>

app/views/contents/index.html.erb
<% title "Materiales - #{@project.title}" %>

<%= content_for :header do %>
    <h1><%= @project.title %></h1>
    <ul class="navigator">
      <li>Intro</li>
      <span>|</span>
      <li><%= link_to 'Materiales', project_contents_path(@project) %></li>
    </ul>
<% end %>


<%= render :partial => 'contents' %>

app/views/contents/show.html.erb
<% title content.title %>

<%= render_top :contents %>
<div class="row24">
  <div id="browser" class="col-left">
    <%= link_to image_tag('iconos/libro.png'), project %>
    <%= render_browser :contents, contents %>
  </div>
  <div class="col-center-left">
    <% content.assets.each do |asset| %>
        <%= image_tag asset.file.url %>
    <% end %>
    &nbsp;
  </div>
  <div class="col-center-right">
    <h1><%= content.title %></h1>

    <h2><%= content.authors %></h2>
    <%= render_body content %>
    &nbsp;
  </div>
</div>
<div class="row24">
  <div class="col-left">&nbsp;</div>
  <div class="col-main">
    <%= disqus content %>
  </div>
</div>

app/views/contents/show.js.erb
document.title = "<%= escape_javascript("#{@content.title}") %>";
$(".center .page").html("<%= escape_javascript(render("page")) %>");
$(".center .page").show("slide", {direction: "right"}, 500);