config/routes.rb
Bookasite::Application.routes.draw do
  root :to => 'series#index'

  # AJAX
  resources :boks

  match "/auth/:provider/callback" => "sessions#create"
  match "/cerrar" => "sessions#destroy", :as => :logout
  match "/identificarse" => "sessions#new", :as => :login
  match "/enter/:id" => "sessions#enter", :as => :enter
  match "/work" => "jobs#work", :as => :work
  match "/admin" => "admin/versions#index"

  # PUBLIC
    scope(:path_names => {:new => "nuevo", :edit => "editar"}) do
    scope "/admin" do
      resources :pages, :path => 'paginas'
      resources :users, :path => 'participantes' do
        resources :invitations, :path => 'invitaciones'
        resources :email_notifications, :path => 'email', :only => :create
      end
      resources :jobs, :path => 'trabajos'
      resources :activities, :path => 'actividad'
      resources :versions, :path => 'versiones'
      resources :notifications, :path => 'subscripciones'
    end

    scope "/models" do
      resources :topics, :only => :show
      resources :asambleas, :only => :show
      resources :calls, :only => :show
      resources :contents, :only => :show
      resources :comments, :only => :show
      resources :answers, :only => :show
    end

    resources :series

    resources :topics do
      resources :answers
      resources :comments
    end
    resources :answers do
      resources :comments
    end


    resources :projects, :path => '' do
      resources :permissions, :path => 'participantes'
      resources :contents, :path => 'materiales'
      resources :asambleas, :path => 'edicion' do
        resources :topics, :path => 't'
      end
      resources :calls, :path => "intro" do
        get :view, :on => :collection, :path => 'ver'
      end
      resources :proposals, :path => 'propuestas' do
        get :view, :on => :collection, :path => 'ver'
      end

    end
  end


end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  respond_to :html

  expose(:series) { Serie.all }
  expose(:serie)
  # index
  expose(:page) { Page.get('/') }
  expose(:info) { Page.get('info') }

  def index
  end

  def show
  end
end

app/views/series/_browser.html.erb
<ul class="browser">
  <h2>Series</h2>
  <% series.each do |serie| %>
      <%= content_tag_for :li, serie do %>
          <h3><%= link_to serie.title, serie %></h3>
      <% end %>
  <% end %>
</ul>
<%= link_to image_tag('logos/LOGO-VIBOK.png', :alt => 'vibok', :id => 'logo-vibok'), 'http://www.edicionesvibok.net' %>

app/views/series/_header.html.erb
<%= content_tag (project? ? :h2 : :h1), serie.title %>
<ul class="navigator">
  <% Serie.all.each do |serie| %>
      <li><%= link_to_unless_current serie.title, serie %></li>
      <span>|</span>
  <% end %>
</ul>

app/views/series/index.html.erb
<% title page.title %>

<%= render_top do %>
    <h1>booka</h1>
    <h4>plataforma editorial abierta</h4>
    <%= button_group do %>
        <% if can? :manage, Serie %>
            <%= add_button_link_to 'Crear una serie', new_series_path, :id => "new_serie_link" %>
        <% end %>
        <%= edit_button_link_to('Editar página', edit_page_path(page)) if can? :edit, page %>
    <% end %>
<% end %>


<div class="row24">
  <div id="browser" class="col-left">
    <%= link_to image_tag('iconos/booka.png'), root_path %>
    <%= render_browser :series, series %>
  </div>
  <div class="col-center editable" data-page="<%= page.id %>">
    <%= render_body page %>
    <%= disqus page %>
  </div>
  <div id="info" class="col-right">
    <%= render_body info %>
  </div>
</div>

app/views/series/show.html.erb
<% title serie.title %>

<%= render_top do %>
    <%= render :partial => 'series/header', :locals => {:serie => serie} %>
<% end %>

<div class="row24">
  <div id="browser" class="col-left">
    <%= link_to image_tag(serie.icon_path, :alt => serie.title), root_path %>
    <%= render_browser :projects, serie.projects %>

  </div>
  <div class="col-center">
    <%= render_body serie %>
    <%= disqus serie %>
  </div>
  <div id="info" class="col-right">
    <%= render_body serie.page %>
  </div>
</div>